
name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect base branch option
        id: detect_bb
        uses: actions/github-script@v7
        with:
          script: |
            const core    = require('@actions/core');
            const payload = context.payload;
            const body =
              payload.comment?.body ??
              payload.review?.body  ??
              payload.issue?.body   ?? '';

            const m = body.match(/-bb\s+([^\s]+)/i);
            core.setOutput('base_branch', m ? m[1] : 'develop');
            console.log(`Base branch set to: ${m ? m[1] : 'develop'}`);

      - name: Run Claude PR Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at:  ${{ secrets.CLAUDE_EXPIRES_AT }}

          model: 'claude-sonnet-4-20250514'
          base_branch: ${{ steps.detect_bb.outputs.base_branch }}
          timeout_minutes: "60"
